nodes: 1000
graph: "datasets/notredame.zip"
template_files: []
text_file: null
output_dir: null
s3:
    use: false
    aws_access_key: null
    aws_secret_key: null
    bucket_name: "ponzi"
    public_view: true